<?php
return array(
	array('code' => 'US', 'name' => 'United States', 'currency_code' => 'USD'),
	array('code' => 'CA', 'name' => 'Canada', 'currency_code' => 'CAD'),
	array('code' => 'AF', 'name' => 'Afghanistan', 'currency_code' => 'AFN'),
	array('code' => 'AL', 'name' => 'Albania', 'currency_code' => 'ALL'),
	array('code' => 'DZ', 'name' => 'Algeria', 'currency_code' => 'DZD'),
	array('code' => 'AS', 'name' => 'American Samoa', 'currency_code' => 'USD'),
	array('code' => 'AD', 'name' => 'Andorra', 'currency_code' => 'EUR'),
	array('code' => 'AO', 'name' => 'Angola', 'currency_code' => 'AOA'),
	array('code' => 'AI', 'name' => 'Anguilla', 'currency_code' => 'XCD'),
	array('code' => 'AQ', 'name' => 'Antarctica', 'currency_code' => ''),
	array('code' => 'AG', 'name' => 'Antigua and/or Barbuda', 'currency_code' => 'XCD'),
	array('code' => 'AR', 'name' => 'Argentina', 'currency_code' => 'ARS'),
	array('code' => 'AM', 'name' => 'Armenia', 'currency_code' => 'AMD'),
	array('code' => 'AW', 'name' => 'Aruba', 'currency_code' => 'AWG'),
	array('code' => 'AU', 'name' => 'Australia', 'currency_code' => 'AUD'),
	array('code' => 'AT', 'name' => 'Austria', 'currency_code' => 'EUR'),
	array('code' => 'AZ', 'name' => 'Azerbaijan', 'currency_code' => 'AZN'),
	array('code' => 'BS', 'name' => 'Bahamas', 'currency_code' => 'BSD'),
	array('code' => 'BH', 'name' => 'Bahrain', 'currency_code' => 'BHD'),
	array('code' => 'BD', 'name' => 'Bangladesh', 'currency_code' => 'BDT'),
	array('code' => 'BB', 'name' => 'Barbados', 'currency_code' => 'BBD'),
	array('code' => 'BY', 'name' => 'Belarus', 'currency_code' => 'BYN'),
	array('code' => 'BE', 'name' => 'Belgium', 'currency_code' => 'EUR'),
	array('code' => 'BZ', 'name' => 'Belize', 'currency_code' => 'BZD'),
	array('code' => 'BJ', 'name' => 'Benin', 'currency_code' => 'XOF'),
	array('code' => 'BM', 'name' => 'Bermuda', 'currency_code' => 'BMD'),
	array('code' => 'BT', 'name' => 'Bhutan', 'currency_code' => 'BTN'),
	array('code' => 'BO', 'name' => 'Bolivia', 'currency_code' => 'BOB'),
	array('code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'currency_code' => 'BAM'),
	array('code' => 'BW', 'name' => 'Botswana', 'currency_code' => 'BWP'),
	array('code' => 'BV', 'name' => 'Bouvet Island', 'currency_code' => ''),
	array('code' => 'BR', 'name' => 'Brazil', 'currency_code' => 'BRL'),
	array('code' => 'IO', 'name' => 'British lndian Ocean Territory', 'currency_code' => 'USD'),
	array('code' => 'BN', 'name' => 'Brunei Darussalam', 'currency_code' => 'BND'),
	array('code' => 'BG', 'name' => 'Bulgaria', 'currency_code' => 'BGN'),
	array('code' => 'BF', 'name' => 'Burkina Faso', 'currency_code' => 'XOF'),
	array('code' => 'BI', 'name' => 'Burundi', 'currency_code' => 'BIF'),
	array('code' => 'KH', 'name' => 'Cambodia', 'currency_code' => 'KHR'),
	array('code' => 'CM', 'name' => 'Cameroon', 'currency_code' => 'XAF'),
	array('code' => 'CV', 'name' => 'Cape Verde', 'currency_code' => 'CVE'),
	array('code' => 'KY', 'name' => 'Cayman Islands', 'currency_code' => 'KYD'),
	array('code' => 'CF', 'name' => 'Central African Republic', 'currency_code' => 'XAF'),
	array('code' => 'TD', 'name' => 'Chad', 'currency_code' => 'XAF'),
	array('code' => 'CL', 'name' => 'Chile', 'currency_code' => 'CLP'),
	array('code' => 'CN', 'name' => 'China', 'currency_code' => 'CNY'),
	array('code' => 'CX', 'name' => 'Christmas Island', 'currency_code' => 'AUD'),
	array('code' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'currency_code' => 'AUD'),
	array('code' => 'CO', 'name' => 'Colombia', 'currency_code' => 'COP'),
	array('code' => 'KM', 'name' => 'Comoros', 'currency_code' => 'KMF'),
	array('code' => 'CG', 'name' => 'Congo', 'currency_code' => 'XAF'),
	array('code' => 'CK', 'name' => 'Cook Islands', 'currency_code' => 'NZD'),
	array('code' => 'CR', 'name' => 'Costa Rica', 'currency_code' => 'CRC'),
	array('code' => 'HR', 'name' => 'Croatia (Hrvatska)', 'currency_code' => 'HRK'),
	array('code' => 'CU', 'name' => 'Cuba', 'currency_code' => 'CUP'),
	array('code' => 'CY', 'name' => 'Cyprus', 'currency_code' => 'EUR'),
	array('code' => 'CZ', 'name' => 'Czech Republic', 'currency_code' => 'CZK'),
	array('code' => 'CD', 'name' => 'Democratic Republic of Congo', 'currency_code' => 'CDF'),
	array('code' => 'DK', 'name' => 'Denmark', 'currency_code' => 'DKK'),
	array('code' => 'DJ', 'name' => 'Djibouti', 'currency_code' => 'DJF'),
	array('code' => 'DM', 'name' => 'Dominica', 'currency_code' => 'XCD'),
	array('code' => 'DO', 'name' => 'Dominican Republic', 'currency_code' => 'DOP'),
	array('code' => 'TP', 'name' => 'East Timor', 'currency_code' => 'USD'),
	array('code' => 'EC', 'name' => 'Ecudaor', 'currency_code' => 'USD'),
	array('code' => 'EG', 'name' => 'Egypt', 'currency_code' => 'EGP'),
	array('code' => 'SV', 'name' => 'El Salvador', 'currency_code' => 'USD'),
	array('code' => 'GQ', 'name' => 'Equatorial Guinea', 'currency_code' => 'XAF'),
	array('code' => 'ER', 'name' => 'Eritrea', 'currency_code' => 'ERN'),
	array('code' => 'EE', 'name' => 'Estonia', 'currency_code' => 'EUR'),
	array('code' => 'ET', 'name' => 'Ethiopia', 'currency_code' => 'ETB'),
	array('code' => 'FK', 'name' => 'Falkland Islands (Malvinas)', 'currency_code' => 'FKP'),
	array('code' => 'FO', 'name' => 'Faroe Islands', 'currency_code' => 'DKK'),
	array('code' => 'FJ', 'name' => 'Fiji', 'currency_code' => 'FJD'),
	array('code' => 'FI', 'name' => 'Finland', 'currency_code' => 'EUR'),
	array('code' => 'FR', 'name' => 'France', 'currency_code' => 'EUR'),
	array('code' => 'FX', 'name' => 'France, Metropolitan', 'currency_code' => 'EUR'),
	array('code' => 'GF', 'name' => 'French Guiana', 'currency_code' => 'EUR'),
	array('code' => 'PF', 'name' => 'French Polynesia', 'currency_code' => 'XPF'),
	array('code' => 'TF', 'name' => 'French Southern Territories', 'currency_code' => 'EUR'),
	array('code' => 'GA', 'name' => 'Gabon', 'currency_code' => 'XAF'),
	array('code' => 'GM', 'name' => 'Gambia', 'currency_code' => 'GMD'),
	array('code' => 'GE', 'name' => 'Georgia', 'currency_code' => 'GEL'),
	array('code' => 'DE', 'name' => 'Germany', 'currency_code' => 'EUR'),
	array('code' => 'GH', 'name' => 'Ghana', 'currency_code' => 'GHS'),
	array('code' => 'GI', 'name' => 'Gibraltar', 'currency_code' => 'GIP'),
	array('code' => 'GR', 'name' => 'Greece', 'currency_code' => 'EUR'),
	array('code' => 'GL', 'name' => 'Greenland', 'currency_code' => 'DKK'),
	array('code' => 'GD', 'name' => 'Grenada', 'currency_code' => 'XCD'),
	array('code' => 'GP', 'name' => 'Guadeloupe', 'currency_code' => 'EUR'),
	array('code' => 'GU', 'name' => 'Guam', 'currency_code' => 'USD'),
	array('code' => 'GT', 'name' => 'Guatemala', 'currency_code' => 'GTQ'),
	array('code' => 'GN', 'name' => 'Guinea', 'currency_code' => 'GNF'),
	array('code' => 'GW', 'name' => 'Guinea-Bissau', 'currency_code' => 'XOF'),
	array('code' => 'GY', 'name' => 'Guyana', 'currency_code' => 'GYD'),
	array('code' => 'HT', 'name' => 'Haiti', 'currency_code' => 'HTG'),
	array('code' => 'HM', 'name' => 'Heard and Mc Donald Islands', 'currency_code' => ''),
	array('code' => 'HN', 'name' => 'Honduras', 'currency_code' => 'HNL'),
	array('code' => 'HK', 'name' => 'Hong Kong', 'currency_code' => 'HKD'),
	array('code' => 'HU', 'name' => 'Hungary', 'currency_code' => 'HUF'),
	array('code' => 'IS', 'name' => 'Iceland', 'currency_code' => 'ISK'),
	array('code' => 'IN', 'name' => 'India', 'currency_code' => 'INR'),
	array('code' => 'ID', 'name' => 'Indonesia', 'currency_code' => 'IDR'),
	array('code' => 'IR', 'name' => 'Iran (Islamic Republic of)', 'currency_code' => 'IRR'),
	array('code' => 'IQ', 'name' => 'Iraq', 'currency_code' => 'IQD'),
	array('code' => 'IE', 'name' => 'Ireland', 'currency_code' => 'EUR'),
	array('code' => 'IL', 'name' => 'Israel', 'currency_code' => 'ILS'),
	array('code' => 'IT', 'name' => 'Italy', 'currency_code' => 'EUR'),
	array('code' => 'CI', 'name' => 'Ivory Coast', 'currency_code' => 'XOF'),
	array('code' => 'JM', 'name' => 'Jamaica', 'currency_code' => 'JMD'),
	array('code' => 'JP', 'name' => 'Japan', 'currency_code' => 'JPY'),
	array('code' => 'JO', 'name' => 'Jordan', 'currency_code' => 'JOD'),
	array('code' => 'KZ', 'name' => 'Kazakhstan', 'currency_code' => 'KZT'),
	array('code' => 'KE', 'name' => 'Kenya', 'currency_code' => 'KES'),
	array('code' => 'KI', 'name' => 'Kiribati', 'currency_code' => 'AUD'),
	array('code' => 'KP', 'name' => 'Korea, Democratic People\'s Republic of', 'currency_code' => 'KPW'),
	array('code' => 'KR', 'name' => 'Korea, Republic of', 'currency_code' => 'KRW'),
	array('code' => 'KW', 'name' => 'Kuwait', 'currency_code' => 'KWD'),
	array('code' => 'KG', 'name' => 'Kyrgyzstan', 'currency_code' => 'KGS'),
	array('code' => 'LA', 'name' => 'Lao People\'s Democratic Republic', 'currency_code' => 'LAK'),
	array('code' => 'LV', 'name' => 'Latvia', 'currency_code' => 'EUR'),
	array('code' => 'LB', 'name' => 'Lebanon', 'currency_code' => 'LBP'),
	array('code' => 'LS', 'name' => 'Lesotho', 'currency_code' => 'LSL'),
	array('code' => 'LR', 'name' => 'Liberia', 'currency_code' => 'LRD'),
	array('code' => 'LY', 'name' => 'Libyan Arab Jamahiriya', 'currency_code' => 'LYD'),
	array('code' => 'LI', 'name' => 'Liechtenstein', 'currency_code' => 'CHF'),
	array('code' => 'LT', 'name' => 'Lithuania', 'currency_code' => 'EUR'),
	array('code' => 'LU', 'name' => 'Luxembourg', 'currency_code' => 'EUR'),
	array('code' => 'MO', 'name' => 'Macau', 'currency_code' => 'MOP'),
	array('code' => 'MK', 'name' => 'Macedonia', 'currency_code' => 'MKD'),
	array('code' => 'MG', 'name' => 'Madagascar', 'currency_code' => 'MGA'),
	array('code' => 'MW', 'name' => 'Malawi', 'currency_code' => 'MWK'),
	array('code' => 'MY', 'name' => 'Malaysia', 'currency_code' => 'MYR'),
	array('code' => 'MV', 'name' => 'Maldives', 'currency_code' => 'MVR'),
	array('code' => 'ML', 'name' => 'Mali', 'currency_code' => 'XOF'),
	array('code' => 'MT', 'name' => 'Malta', 'currency_code' => 'EUR'),
	array('code' => 'MH', 'name' => 'Marshall Islands', 'currency_code' => 'USD'),
	array('code' => 'MQ', 'name' => 'Martinique', 'currency_code' => 'EUR'),
	array('code' => 'MR', 'name' => 'Mauritania', 'currency_code' => 'MRU'),
	array('code' => 'MU', 'name' => 'Mauritius', 'currency_code' => 'MUR'),
	array('code' => 'TY', 'name' => 'Mayotte', 'currency_code' => 'EUR'),
	array('code' => 'MX', 'name' => 'Mexico', 'currency_code' => 'MXN'),
	array('code' => 'FM', 'name' => 'Micronesia, Federated States of', 'currency_code' => 'USD'),
	array('code' => 'MD', 'name' => 'Moldova, Republic of', 'currency_code' => 'MDL'),
	array('code' => 'MC', 'name' => 'Monaco', 'currency_code' => 'EUR'),
	array('code' => 'MN', 'name' => 'Mongolia', 'currency_code' => 'MNT'),
	array('code' => 'MS', 'name' => 'Montserrat', 'currency_code' => 'XCD'),
	array('code' => 'MA', 'name' => 'Morocco', 'currency_code' => 'MAD'),
	array('code' => 'MZ', 'name' => 'Mozambique', 'currency_code' => 'MZN'),
	array('code' => 'MM', 'name' => 'Myanmar', 'currency_code' => 'MMK'),
	array('code' => 'NA', 'name' => 'Namibia', 'currency_code' => 'NAD'),
	array('code' => 'NR', 'name' => 'Nauru', 'currency_code' => 'AUD'),
	array('code' => 'NP', 'name' => 'Nepal', 'currency_code' => 'NPR'),
	array('code' => 'NL', 'name' => 'Netherlands', 'currency_code' => 'EUR'),
	array('code' => 'AN', 'name' => 'Netherlands Antilles', 'currency_code' => 'ANG'),
	array('code' => 'NC', 'name' => 'New Caledonia', 'currency_code' => 'XPF'),
	array('code' => 'NZ', 'name' => 'New Zealand', 'currency_code' => 'NZD'),
	array('code' => 'NI', 'name' => 'Nicaragua', 'currency_code' => 'NIO'),
	array('code' => 'NE', 'name' => 'Niger', 'currency_code' => 'XOF'),
	array('code' => 'NG', 'name' => 'Nigeria', 'currency_code' => 'NGN'),
	array('code' => 'NU', 'name' => 'Niue', 'currency_code' => 'NZD'),
	array('code' => 'NF', 'name' => 'Norfolk Island', 'currency_code' => 'AUD'),
	array('code' => 'MP', 'name' => 'Northern Mariana Islands', 'currency_code' => 'USD'),
	array('code' => 'NO', 'name' => 'Norway', 'currency_code' => 'NOK'),
	array('code' => 'OM', 'name' => 'Oman', 'currency_code' => 'OMR'),
	array('code' => 'PK', 'name' => 'Pakistan', 'currency_code' => 'PKR'),
	array('code' => 'PW', 'name' => 'Palau', 'currency_code' => 'USD'),
	array('code' => 'PA', 'name' => 'Panama', 'currency_code' => 'PAB'),
	array('code' => 'PG', 'name' => 'Papua New Guinea', 'currency_code' => 'PGK'),
	array('code' => 'PY', 'name' => 'Paraguay', 'currency_code' => 'PYG'),
	array('code' => 'PE', 'name' => 'Peru', 'currency_code' => 'PEN'),
	array('code' => 'PH', 'name' => 'Philippines', 'currency_code' => 'PHP'),
	array('code' => 'PN', 'name' => 'Pitcairn', 'currency_code' => 'NZD'),
	array('code' => 'PL', 'name' => 'Poland', 'currency_code' => 'PLN'),
	array('code' => 'PT', 'name' => 'Portugal', 'currency_code' => 'EUR'),
	array('code' => 'PR', 'name' => 'Puerto Rico', 'currency_code' => 'USD'),
	array('code' => 'QA', 'name' => 'Qatar', 'currency_code' => 'QAR'),
	array('code' => 'SS', 'name' => 'Republic of South Sudan', 'currency_code' => 'SSP'),
	array('code' => 'RE', 'name' => 'Reunion', 'currency_code' => 'EUR'),
	array('code' => 'RO', 'name' => 'Romania', 'currency_code' => 'RON'),
	array('code' => 'RU', 'name' => 'Russian Federation', 'currency_code' => 'RUB'),
	array('code' => 'RW', 'name' => 'Rwanda', 'currency_code' => 'RWF'),
	array('code' => 'KN', 'name' => 'Saint Kitts and Nevis', 'currency_code' => 'XCD'),
	array('code' => 'LC', 'name' => 'Saint Lucia', 'currency_code' => 'XCD'),
	array('code' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'currency_code' => 'XCD'),
	array('code' => 'WS', 'name' => 'Samoa', 'currency_code' => 'WST'),
	array('code' => 'SM', 'name' => 'San Marino', 'currency_code' => 'EUR'),
	array('code' => 'ST', 'name' => 'Sao Tome and Principe', 'currency_code' => 'STN'),
	array('code' => 'SA', 'name' => 'Saudi Arabia', 'currency_code' => 'SAR'),
	array('code' => 'SN', 'name' => 'Senegal', 'currency_code' => 'XOF'),
	array('code' => 'RS', 'name' => 'Serbia', 'currency_code' => 'RSD'),
	array('code' => 'SC', 'name' => 'Seychelles', 'currency_code' => 'SCR'),
	array('code' => 'SL', 'name' => 'Sierra Leone', 'currency_code' => 'SLL'),
	array('code' => 'SG', 'name' => 'Singapore', 'currency_code' => 'SGD'),
	array('code' => 'SK', 'name' => 'Slovakia', 'currency_code' => 'EUR'),
	array('code' => 'SI', 'name' => 'Slovenia', 'currency_code' => 'EUR'),
	array('code' => 'SB', 'name' => 'Solomon Islands', 'currency_code' => 'SBD'),
	array('code' => 'SO', 'name' => 'Somalia', 'currency_code' => 'SOS'),
	array('code' => 'ZA', 'name' => 'South Africa', 'currency_code' => 'ZAR'),
	array('code' => 'GS', 'name' => 'South Georgia South Sandwich Islands', 'currency_code' => 'GBP'),
	array('code' => 'ES', 'name' => 'Spain', 'currency_code' => 'EUR'),
	array('code' => 'LK', 'name' => 'Sri Lanka', 'currency_code' => 'LKR'),
	array('code' => 'SH', 'name' => 'St. Helena', 'currency_code' => 'SHP'),
	array('code' => 'PM', 'name' => 'St. Pierre and Miquelon', 'currency_code' => 'EUR'),
	array('code' => 'SD', 'name' => 'Sudan', 'currency_code' => 'SDG'),
	array('code' => 'SR', 'name' => 'Suriname', 'currency_code' => 'SRD'),
	array('code' => 'SJ', 'name' => 'Svalbard and Jan Mayen Islands', 'currency_code' => 'NOK'),
	array('code' => 'SZ', 'name' => 'Swaziland', 'currency_code' => 'SZL'),
	array('code' => 'SE', 'name' => 'Sweden', 'currency_code' => 'SEK'),
	array('code' => 'CH', 'name' => 'Switzerland', 'currency_code' => 'CHF'),
	array('code' => 'SY', 'name' => 'Syrian Arab Republic', 'currency_code' => 'SYP'),
	array('code' => 'TW', 'name' => 'Taiwan', 'currency_code' => 'TWD'),
	array('code' => 'TJ', 'name' => 'Tajikistan', 'currency_code' => 'TJS'),
	array('code' => 'TZ', 'name' => 'Tanzania, United Republic of', 'currency_code' => 'TZS'),
	array('code' => 'TH', 'name' => 'Thailand', 'currency_code' => 'THB'),
	array('code' => 'TG', 'name' => 'Togo', 'currency_code' => 'XOF'),
	array('code' => 'TK', 'name' => 'Tokelau', 'currency_code' => 'NZD'),
	array('code' => 'TO', 'name' => 'Tonga', 'currency_code' => 'TOP'),
	array('code' => 'TT', 'name' => 'Trinidad and Tobago', 'currency_code' => 'TTD'),
	array('code' => 'TN', 'name' => 'Tunisia', 'currency_code' => 'TND'),
	array('code' => 'TR', 'name' => 'Turkey', 'currency_code' => 'TRY'),
	array('code' => 'TM', 'name' => 'Turkmenistan', 'currency_code' => 'TMT'),
	array('code' => 'TC', 'name' => 'Turks and Caicos Islands', 'currency_code' => 'USD'),
	array('code' => 'TV', 'name' => 'Tuvalu', 'currency_code' => 'AUD'),
	array('code' => 'UG', 'name' => 'Uganda', 'currency_code' => 'UGX'),
	array('code' => 'UA', 'name' => 'Ukraine', 'currency_code' => 'UAH'),
	array('code' => 'AE', 'name' => 'United Arab Emirates', 'currency_code' => 'AED'),
	array('code' => 'GB', 'name' => 'United Kingdom', 'currency_code' => 'GBP'),
	array('code' => 'UM', 'name' => 'United States minor outlying islands', 'currency_code' => 'USD'),
	array('code' => 'UY', 'name' => 'Uruguay', 'currency_code' => 'UYU'),
	array('code' => 'UZ', 'name' => 'Uzbekistan', 'currency_code' => 'UZS'),
	array('code' => 'VU', 'name' => 'Vanuatu', 'currency_code' => 'VUV'),
	array('code' => 'VA', 'name' => 'Vatican City State', 'currency_code' => 'EUR'),
	array('code' => 'VE', 'name' => 'Venezuela', 'currency_code' => 'VES'),
	array('code' => 'VN', 'name' => 'Vietnam', 'currency_code' => 'VND'),
	array('code' => 'VG', 'name' => 'Virgin Islands (British)', 'currency_code' => 'USD'),
	array('code' => 'VI', 'name' => 'Virgin Islands (U.S.)', 'currency_code' => 'USD'),
	array('code' => 'WF', 'name' => 'Wallis and Futuna Islands', 'currency_code' => 'XPF'),
	array('code' => 'EH', 'name' => 'Western Sahara', 'currency_code' => 'MAD'),
	array('code' => 'YE', 'name' => 'Yemen', 'currency_code' => 'YER'),
	array('code' => 'YU', 'name' => 'Yugoslavia', 'currency_code' => 'YUM'),
	array('code' => 'ZR', 'name' => 'Zaire', 'currency_code' => 'ZRZ'),
	array('code' => 'ZM', 'name' => 'Zambia', 'currency_code' => 'ZMW'),
	array('code' => 'ZW', 'name' => 'Zimbabwe', 'currency_code' => 'ZWL'),
);
